"""initial schema

Revision ID: aeb65a337545
Revises: 
Create Date: 2026-06-10 12:52:15.777709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aeb65a337545'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ergast_ref', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('locality', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('alt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_circuits'))
    )
    op.create_index(op.f('ix_circuits_ergast_ref'), 'circuits', ['ergast_ref'], unique=True)
    op.create_table('constructors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ergast_ref', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('nationality', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('logo_url', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_constructors'))
    )
    op.create_index(op.f('ix_constructors_ergast_ref'), 'constructors', ['ergast_ref'], unique=True)
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ergast_ref', sa.String(length=64), nullable=False),
    sa.Column('permanent_number', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=3), nullable=True),
    sa.Column('forename', sa.String(length=64), nullable=False),
    sa.Column('surname', sa.String(length=64), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drivers'))
    )
    op.create_index(op.f('ix_drivers_ergast_ref'), 'drivers', ['ergast_ref'], unique=True)
    op.create_table('seasons',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year', name=op.f('pk_seasons'))
    )
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statuses')),
    sa.UniqueConstraint('label', name=op.f('uq_statuses_label'))
    )
    op.create_table('grand_prix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=False),
    sa.Column('race_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], name=op.f('fk_grand_prix_circuit_id_circuits')),
    sa.ForeignKeyConstraint(['season_year'], ['seasons.year'], name=op.f('fk_grand_prix_season_year_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grand_prix')),
    sa.UniqueConstraint('season_year', 'round', name=op.f('uq_grand_prix_season_year'))
    )
    op.create_index(op.f('ix_grand_prix_circuit_id'), 'grand_prix', ['circuit_id'], unique=False)
    op.create_table('season_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.id'], name=op.f('fk_season_entries_constructor_id_constructors')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_season_entries_driver_id_drivers')),
    sa.ForeignKeyConstraint(['season_year'], ['seasons.year'], name=op.f('fk_season_entries_season_year_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_season_entries')),
    sa.UniqueConstraint('season_year', 'driver_id', name=op.f('uq_season_entries_season_year'))
    )
    op.create_index(op.f('ix_season_entries_constructor_id'), 'season_entries', ['constructor_id'], unique=False)
    op.create_index(op.f('ix_season_entries_driver_id'), 'season_entries', ['driver_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grand_prix_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('fp1', 'fp2', 'fp3', 'sprint_qualifying', 'qualifying', 'sprint', 'race', name='session_type', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('openf1_session_key', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grand_prix_id'], ['grand_prix.id'], name=op.f('fk_sessions_grand_prix_id_grand_prix')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('grand_prix_id', 'type', name=op.f('uq_sessions_grand_prix_id')),
    sa.UniqueConstraint('openf1_session_key', name=op.f('uq_sessions_openf1_session_key'))
    )
    op.create_index(op.f('ix_sessions_grand_prix_id'), 'sessions', ['grand_prix_id'], unique=False)
    op.create_table('laps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('lap_duration', sa.Float(), nullable=True),
    sa.Column('sector1_ms', sa.Integer(), nullable=True),
    sa.Column('sector2_ms', sa.Integer(), nullable=True),
    sa.Column('sector3_ms', sa.Integer(), nullable=True),
    sa.Column('is_pit_out_lap', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_laps_driver_id_drivers')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_laps_session_id_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_laps')),
    sa.UniqueConstraint('session_id', 'driver_id', 'lap_number', name=op.f('uq_laps_session_id'))
    )
    op.create_table('live_timing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('gap_to_leader_ms', sa.Integer(), nullable=True),
    sa.Column('interval_ahead_ms', sa.Integer(), nullable=True),
    sa.Column('last_lap_ms', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_live_timing_driver_id_drivers')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_live_timing_session_id_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_live_timing')),
    sa.UniqueConstraint('session_id', 'driver_id', 'lap_number', name=op.f('uq_live_timing_session_id'))
    )
    op.create_index('ix_live_timing_session_lap', 'live_timing', ['session_id', 'lap_number'], unique=False)
    op.create_table('pit_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('stop_number', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_pit_stops_driver_id_drivers')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_pit_stops_session_id_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pit_stops')),
    sa.UniqueConstraint('session_id', 'driver_id', 'stop_number', name=op.f('uq_pit_stops_session_id'))
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('lap_checkpoint', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_predictions_session_id_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions')),
    sa.UniqueConstraint('session_id', 'lap_checkpoint', 'model_version', name=op.f('uq_predictions_session_id'))
    )
    op.create_index('ix_predictions_payload', 'predictions', ['payload'], unique=False, postgresql_using='gin')
    op.create_table('qualifying',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('q1', sa.String(length=16), nullable=True),
    sa.Column('q2', sa.String(length=16), nullable=True),
    sa.Column('q3', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.id'], name=op.f('fk_qualifying_constructor_id_constructors')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_qualifying_driver_id_drivers')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_qualifying_session_id_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qualifying')),
    sa.UniqueConstraint('session_id', 'driver_id', name=op.f('uq_qualifying_session_id'))
    )
    op.create_index(op.f('ix_qualifying_driver_id'), 'qualifying', ['driver_id'], unique=False)
    op.create_table('session_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('grid', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('points', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('laps_completed', sa.Integer(), nullable=True),
    sa.Column('fastest_lap_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.id'], name=op.f('fk_session_results_constructor_id_constructors')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_session_results_driver_id_drivers')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_results_session_id_sessions')),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], name=op.f('fk_session_results_status_id_statuses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_results')),
    sa.UniqueConstraint('session_id', 'driver_id', name=op.f('uq_session_results_session_id'))
    )
    op.create_index(op.f('ix_session_results_constructor_id'), 'session_results', ['constructor_id'], unique=False)
    op.create_index(op.f('ix_session_results_driver_id'), 'session_results', ['driver_id'], unique=False)
    op.create_table('stints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('stint_number', sa.Integer(), nullable=False),
    sa.Column('compound', sa.String(length=16), nullable=True),
    sa.Column('lap_start', sa.Integer(), nullable=False),
    sa.Column('lap_end', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_stints_driver_id_drivers')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_stints_session_id_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stints')),
    sa.UniqueConstraint('session_id', 'driver_id', 'stint_number', name=op.f('uq_stints_session_id'))
    )
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('air_temp', sa.Float(), nullable=True),
    sa.Column('track_temp', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('rainfall', sa.Boolean(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_dir', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_weather_session_id_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather'))
    )
    op.create_index(op.f('ix_weather_session_id'), 'weather', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_session_id'), table_name='weather')
    op.drop_table('weather')
    op.drop_table('stints')
    op.drop_index(op.f('ix_session_results_driver_id'), table_name='session_results')
    op.drop_index(op.f('ix_session_results_constructor_id'), table_name='session_results')
    op.drop_table('session_results')
    op.drop_index(op.f('ix_qualifying_driver_id'), table_name='qualifying')
    op.drop_table('qualifying')
    op.drop_index('ix_predictions_payload', table_name='predictions', postgresql_using='gin')
    op.drop_table('predictions')
    op.drop_table('pit_stops')
    op.drop_index('ix_live_timing_session_lap', table_name='live_timing')
    op.drop_table('live_timing')
    op.drop_table('laps')
    op.drop_index(op.f('ix_sessions_grand_prix_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_season_entries_driver_id'), table_name='season_entries')
    op.drop_index(op.f('ix_season_entries_constructor_id'), table_name='season_entries')
    op.drop_table('season_entries')
    op.drop_index(op.f('ix_grand_prix_circuit_id'), table_name='grand_prix')
    op.drop_table('grand_prix')
    op.drop_table('statuses')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_drivers_ergast_ref'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_constructors_ergast_ref'), table_name='constructors')
    op.drop_table('constructors')
    op.drop_index(op.f('ix_circuits_ergast_ref'), table_name='circuits')
    op.drop_table('circuits')
    # ### end Alembic commands ###
